[package]
name = "rusty_brainfuck"
version = "0.2.0"
authors = ["SuitCase <ubatamamoon@gmail.com>"]
edition = "2018"

[dependencies]

[[example]]
name = "bf_interpreter"
path = "examples/bf_interpreter/main.rs"
